### ISSUE TITLE
[Commands]: Fun

### ISSUE THREAD

**Issue by prarimz** [MoominBot/MoominBot#18]
- [x] [Command]: cuddle command
/cuddle [@user] [reason]
Description: Give someone a cuddle

- [x] [Command]: hug command
/hug < @user > [reason]
Description: Hug someone with love (and fear)

- [x] [Command]: kiss command
/kiss [@user] [reason]
Description: Ask for some kisses / kiss someone

- [x] [Command]: laugh command
/laugh [@user] [reason]
Description: Laugh randomly / laugh at someone

- [x] [Command]: FakeMsgCommand
/fakemsg [@user] [message]
Description: Prank on someone with a fake message through webhook.

**Comment by thenishantsapkota** [comment]
I am starting work on these now.
These work will be done using this [api](https://www.nekos.fun/apidoc.html)

**Comment by thenishantsapkota** [comment]
Tried making all of the commands `Context Menus` based, but the limit provided by Discord was reached.
Reverting all the Context Menus based commands to slash commands for the time being!

**Comment by thenishantsapkota** [comment]
All of the commands are done, except for `bite` and `kill`.
The search for the API Endpoints for those two commands is on.

**Comment by thenishantsapkota** [comment]
Added the `FakeMessage` command, the search for the endpoints for bite and kill commands is still on.
This will be completed as soon as I find the proper endpoints.
