### ISSUE TITLE
[Commands]: Games

### ISSUE THREAD

**Issue by dragonfirefox** [MoominBot/MoominBot#68]
- [ ] [Command]: Calculator
       /calculator
      Description: Calculator using interactive buttons.

- [ ] [Command]: Snake
      /snake
      Description: Play snake game in embed with buttons support.

- [ ] [Command]: Tictactoe 
       /tictactoe **[@user]** (Optional)
       Description: Play tictactoe with bot either specific member.

- [ ] [Command]: Trivia
      /trivia
      Description: Play trivia game.

- [ ] [Command]: QuickClick
      /quickclick
      Description: Quickly click on a button which will show for a certain time (win who'll click first)

**Comment by DevAndromeda** [comment]
- [ ] ~~Calculator~~
- [ ] ~~Snake~~
- [ ] tictactoe*
- [ ] trivia
- [ ] quickclick*

*may not be implemented
? ~~will not be implemented~~
